### ISSUE TITLE
option to center the container

### ISSUE THREAD

**Issue by opetznick** [yconst/Freetile#1]
hi there

first of all - awesome plugin! second.. is there any way to horizontal center the used container?

thanks in advance
oliver

**Comment by Mgamerz** [comment]
I know this is ancient but can someone share their working centering code? I have some things that are being tiled but don't have enough content to even fill the width of the container (just depends on what's there at the time)... it looks terrible with everything on the left and I don't want a fixed width container.

**Comment by Dacius** [comment]
Please don't close those issues without giving an example or documenting the used options.
