### ISSUE TITLE
Disable images loaded by default

### ISSUE THREAD

**Issue by scazzy** [yconst/Freetile#29]
New version of freetile seems to be using images loaded by default. Its a curse.
Until the images are loaded, the grid is scattered wildly, looks ugly, same case with lazy loading, the response data is retrieved and rendered, but they are positioned to the top of the grid overlapping existing grid bricks until the images are loaded.

**Comment by yconst** [comment]
You can take a look at the `.ignore-load-check` selector in order to disable imagesLoaded. Also take a look at the (source of the demo)(http://apex.yconst.com/freetile-demo/js/init.js).
