### ISSUE TITLE
Question: Vertical Offset

### ISSUE THREAD

**Issue by flyonthewall602** [yconst/Freetile#31]
Hi,

I love using Freetile, but I really want all my images to stack without any padding or margin between the tiles. I've been able to remove the side margins, but I have about a 6px space at the bottom of each tile. I would be okay with a 1px space (which appears in your demos, I think)...but 6px is too big.

Is there something I am missing where I can control this? Any advice would help.

Thanks!

**Comment by yconst** [comment]
I came across this issue some time ago, and it turns out it was related with images being measured incorrectly by the browser. Can't remember the fix though..

**Comment by yconst** [comment]
Ah, there you go.. http://stackoverflow.com/questions/7774814/remove-white-space-below-image?lq=1
