### ISSUE TITLE
Rotate elements

### ISSUE THREAD

**Issue by villanus** [yconst/Freetile#35]
We are trying to use freetile to create Sticker sheets of svg images.
It doesn't matter if the svgs are rotated, since the goal is to print them on the smallest paper possible without shrinking the content.

Does freetile support this?

**Comment by yconst** [comment]
Freetile is optimised for presenting oriented sequential content. A such, I don't think it would be the best choice for packing, as in your problem. For that, I'd suggest you to use a bin packing algorithm.
